- hosts: servers
  become: true
  gather_facts: false

  pre_tasks:
    - name: "APPLY: Connect as root on port 22"
      ansible.builtin.set_fact:
        ansible_user: "root"
        # Esto hará que Ansible use las variables de tu Vault automáticamente
        ansible_password: "{{ root_user_password }}"
        # ansible_become_password: "{{ sudo_password_del_vault }}" # if user is a sudoer and not root use uncomment
  roles:
    - os-updates
