- hosts: contabo
  become: false
  gather_facts: false

  pre_tasks:
    - name: Assign user for role
      ansible.builtin.set_fact:
        ansible_user: "root"
        # Esto hará que Ansible use las variables de tu Vault automáticamente
        ansible_password: "{{ root_ansible_password }}" 
        # ansible_become_password: "{{ sudo_password_del_vault }}" # if user is a sudoer and not root use uncomment

    - name: Add host fingerprint to known_hosts
      ansible.builtin.known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"
        path: "~/.ssh/known_hosts"
      delegate_to: localhost
      become: false

  roles:
    - serversprep
