- hosts: servers
  become: false
  gather_facts: false

  pre_tasks:
    - name: "APPLY: Connect as root on port 22"
      ansible.builtin.set_fact:
        ansible_user: "root"
        # Esto hará que Ansible use las variables de tu Vault automáticamente
        ansible_password: "{{ root_user_password }}"
        # ansible_become_password: "{{ sudo_password_del_vault }}" # if user is a sudoer and not root use uncomment

    - name: Add host fingerprint to known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
        path: "~/.ssh/known_hosts"
      delegate_to: localhost
      become: false
      check_mode: false

  roles:
    - serversprep
