#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/deploy-containers
- name: "APPLY: Create Traefik labels dictionary"
  set_fact:
    my_labels: "{{ my_labels | default({}) | combine({ item.key: item.value }) }}"
  with_items:
    - { 'key': 'traefik.enable', 'value': 'true' }
    - { 'key': 'traefik.http.routers.{{ container_name }}-https.tls', 'value': 'true' }
    - { 'key': 'traefik.http.routers.{{ container_name }}-https.tls.certresolver', 'value': 'cloudflare' }
    - { 'key': 'traefik.http.routers.{{ container_name }}-https.rule', 'value': 'Host(`{{ container_name }}.{{ dns_domain }}`)' }
    - { 'key': 'traefik.http.routers.{{ container_name }}-https.entrypoints', 'value': 'websecure' }
    - { 'key': 'traefik.http.routers.{{ container_name }}-https.tls.domains[0].sans', 'value': '*.{{ dns_domain }}' }

- name: "INFO: Traefik labels resolved"
  ansible.builtin.debug:
    msg: "container={{ container_name }} | host={{ container_name }}.{{ dns_domain }} | network={{ docker_network_name }}"

- name: "INFO: Start container through Traefik"
  ansible.builtin.debug:
    msg: "name={{ container_name }} | image={{ container_image }} | network={{ docker_network_name }}"

- name: "APPLY: Start container through Traefik"
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    labels: "{{ my_labels }}"
