#SPDX-License-Identifier: MIT-0
---
# tasks file for serversprep
- name: "INFO: Add host fingerprint to known_hosts"
  ansible.builtin.debug:
    msg: "host={{ ansible_host }} | dest=~/.ssh/known_hosts"

- name: "APPLY: Add host fingerprint to known_hosts"
  ansible.builtin.known_hosts:
    name: "{{ ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
    path: "~/.ssh/known_hosts"

- name: "INFO: Set authorized key on remote"
  ansible.builtin.debug:
    msg: "user={{ ansible_user }} | key=ssh_keys/{{ key_name }}.pub"

- name: "APPLY: Set authorized key on remote"
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', playbook_dir + '/ssh_keys/' + key_name + '.pub') }}"
