#SPDX-License-Identifier: MIT-0
---
# tasks file for os-updates
- name: "INFO: Update all packages"
  ansible.builtin.debug:
    msg: "host={{ inventory_hostname }} | dist-upgrade + autoremove"

- name: "APPLY: Update all packages on a Debian/Ubuntu"
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    cache_valid_time: 3600

- name: "INFO: Check if reboot is required"
  ansible.builtin.debug:
    msg: "checking /var/run/reboot-required on {{ inventory_hostname }}"

- name: "APPLY: Check if reboot is required"
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: "INFO: Reboot the server"
  ansible.builtin.debug:
    msg: "rebooting {{ inventory_hostname }} | timeout=300s | post_reboot_delay=30s"
  when: reboot_required_file.stat.exists

- name: "APPLY: Reboot the server and wait for it to come back"
  reboot:
    msg: "Rebooting to update system libs/kernel"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: "APPLY: Verify new update (optional)"
  command: uname -mrs
  register: uname_result

- name: "INFO: Display new kernel version"
  debug:
    var: uname_result.stdout_lines
