#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/serversconf
- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
    daemon_reload: true

- name: restart ssh.socket
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted
    daemon_reload: true
  when: ansible_facts['distribution'] == "Ubuntu"