#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/deploy-adempiere

adempiere_container_filter: adempiere-ui-gateway
adempiere_container_name: adempiere-ui-gateway
install_path: /opt/development
# repo_url and repo_version are set in group_vars/all/vars.yml — do not set defaults here
be_user: "{{ adempiere_username }}"
postgres_external_port: 5432